version: '3.3'
services:
  spp-platform:
    image: sourceplusplus/spp-platform:latest
    container_name: spp-platform
    hostname: spp-platform
    ports:
      - "11800:11800"
      - "12800:12800"
      - "5106:5106"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5106
      - SPP_LOGGING_LEVEL=trace
      - SW_RECEIVER_GRPC_SSL_ENABLED=false #todo: fix this and config.secure = false
      - SPP_HTTP_SSL_ENABLED=false #todo; Change back to ssl once the library works with self-signed certs
      - SPP_GRPC_SSL_ENABLED=false
