name: Release distributions

on:
  release:
    types: [published]

jobs:
  docker-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
